### ISSUE TITLE
Unable to resolve action `BieggerM/yamllint`, repository not found

### ISSUE THREAD

**Issue by DaveSpe** [BieggerM/yamale-action#1]
My action code
```
name: yamale-action
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: bieggerm/yamllint@v1.53
        name: lint-yaml
        with:
          base_dir: "yaml-templates/" 
          schema: ".github/lint/schema.yaml" 
          include_subdir: false
```

When I submit a PR the check fails
![image](https://github.com/BieggerM/yamale-action/assets/65930418/192dd9a8-b811-4c84-abf6-9a67e6680659)

When I did into the details in the action this is the error I get:
Error: Unable to resolve action `BieggerM/yamllint`, repository not found

![image](https://github.com/BieggerM/yamale-action/assets/65930418/cca34bcc-a016-43e6-9559-25db2fa56e1e)
